#!/bin/bash

commit1=`echo "$1" | grep -Po '^[^:]*'`
commit2=`echo "$1" | grep -Po '(?<=:).*$'`
path=$2

shift; shift

show_zeros=
while (( "$#" ))
do
	case $1 in
		-a|--all)
			show_zeros=y
			shift
			;;
	esac
done

realpath=`readlink -m $path`
if [ ${path: -1} = "/" ]
then
	dir=$realpath"/"
else
	dir=`dirname $realpath`
fi

if ! git -C "$dir" merge-base --is-ancestor $commit1 $commit2
then
	echo "$commit1 is not ancestor of $commit2"
	exit 1
fi

for f in `find $realpath -not \( -path $dir.git -prune \)`
do
	normal_f=${f#$realpath}
	count=`git -C $dir log -p -w --word-diff -U0 $commit1..$commit2 -- $f | tr -d '\r' | grep -Poc '\[\-.+?\-\]\{\+.+?\+\}|\{\+.+?\+\}|\[\-.+?\-\]'`
	if [ $? ]
	then
		if [ "$show_zeros" == "y" ] || (( count > 0 ))
		then
			echo "$normal_f $count"
		fi
	else
		echo "$normal_f ERROR"
	fi
done